### ISSUE TITLE
HLM IOC updates stopped

### ISSUE THREAD

**Issue by mihai-stfc** [ISISNeutronMuon/HLM_PV_Import#2]
Not an issue of the HLM PV Import itself, but one that influences the service.
The HLM IOC (Omron FINS PLC) had been running for approx. 2.5 months, after which it stopped receiving updates.
Although restarting the IOC fixed the issue, its cause is uncertain.

Before, on each day a few errors would be logged.
After 12/15, no more log files were found. 

[FINS_01-20201215.log](https://github.com/ISISNeutronMuon/HLM_PV_Import/files/5765006/FINS_01-20201215.log)
[FINS_01-20201214.log](https://github.com/ISISNeutronMuon/HLM_PV_Import/files/5765009/FINS_01-20201214.log)
[FINS_01-20201213.log](https://github.com/ISISNeutronMuon/HLM_PV_Import/files/5765023/FINS_01-20201213.log)
[FINS_01-20201212.log](https://github.com/ISISNeutronMuon/HLM_PV_Import/files/5765010/FINS_01-20201212.log)
[FINS_01-20201211.log](https://github.com/ISISNeutronMuon/HLM_PV_Import/files/5765012/FINS_01-20201211.log)
[FINS_01-20201210.log](https://github.com/ISISNeutronMuon/HLM_PV_Import/files/5765013/FINS_01-20201210.log)
[FINS_01-20201209.log](https://github.com/ISISNeutronMuon/HLM_PV_Import/files/5765014/FINS_01-20201209.log)
[FINS_01-20201208.log](https://github.com/ISISNeutronMuon/HLM_PV_Import/files/5765015/FINS_01-20201208.log)
[FINS_01-20201207.log](https://github.com/ISISNeutronMuon/HLM_PV_Import/files/5765016/FINS_01-20201207.log)
[FINS_01-20201206.log](https://github.com/ISISNeutronMuon/HLM_PV_Import/files/5765017/FINS_01-20201206.log)
[FINS_01-20201205.log](https://github.com/ISISNeutronMuon/HLM_PV_Import/files/5765018/FINS_01-20201205.log)
[FINS_01-20201204.log](https://github.com/ISISNeutronMuon/HLM_PV_Import/files/5765019/FINS_01-20201204.log)
[FINS_01-20201203.log](https://github.com/ISISNeutronMuon/HLM_PV_Import/files/5765020/FINS_01-20201203.log)
[FINS_01-20201202.log](https://github.com/ISISNeutronMuon/HLM_PV_Import/files/5765021/FINS_01-20201202.log)
[FINS_01-20201201.log](https://github.com/ISISNeutronMuon/HLM_PV_Import/files/5765022/FINS_01-20201201.log)

**Comment by John-Holt-Tessella** [comment]
Is this running on Windows? @FreddieAkeroyd could this be the time rollover bug?

**Comment by FreddieAkeroyd** [comment]
Hi @John-Holt-Tessella  good suggestion, the issue you mention could cause this. 

The issue was fixed on 30th September and will cause an issue at the point the computer the IOC has been running on has been up for a multiple of 49.7 days

@mihai-stfc - do you know if the IOC had the 30th september epics base fix? If the issue occurred after the IOC had been running for more than 49.7 days then this will not be the cause, when did the IOC first start running?

**Comment by mihai-stfc** [comment]
@John-Holt-Tessella Yes, it is running on Windows x64 with IBEX, in procServ. 
Where could I find more info on the time rollover bug? It may have indeed been the cause, as the IOC was running since 10/27 and "stopped" on ~12/15

@FreddieAkeroyd I believe I restarted it on 10/27/20, by looking at the Teams chat. That is when I had an issue with the IBEX server, I got it fixed and since then I don't remember changing anything regarding the IOC besides opening the external gateway just before holidays. I am not sure whether the IOC had the EPICS base fix

Edit: I've had a look through the logs, it started running on 10/27/2020, while the last log is from 12/15/2020, which is 49 days.

**Comment by FreddieAkeroyd** [comment]
The 49 days multiple is actually from a system reboot as it is a system timer that resets, did you reboot the PC around the same time (27/10) ?

**Comment by FreddieAkeroyd** [comment]
For technical details of the underlying issue see ISISComputingGroup/IBEX#5717

**Comment by mihai-stfc** [comment]
@FreddieAkeroyd My PC rebooted on 10/27, it was not manual though, it happened during the night.

**Comment by FreddieAkeroyd** [comment]
OK, so I think the mystery and issue is resolved - the IOC deployed to HEMON from the jenkins build server will already have the necessary fix applied

**Comment by mihai-stfc** [comment]
Good to know, thank you @John-Holt-Tessella and @FreddieAkeroyd !
